definitions:
  caches:
    gopath: /go
  steps:
    - step: &Verify
        caches:
          - gopath
        script:
          - export GO111MODULE=on
          - export GOPROXY=https://proxy.golang.org
          - go version # log the version of Go we are using to test
          - (cd /tmp ; go get honnef.co/go/tools/cmd/staticcheck)
          - PACKAGE_PATH=~/"${BITBUCKET_REPO_OWNER}"/"${BITBUCKET_REPO_SLUG}"
          - mkdir -pv "${PACKAGE_PATH}"
          - tar -cO --exclude-vcs --exclude=bitbucket-pipelines.yml . | tar -xv -C "${PACKAGE_PATH}"
          - cd "${PACKAGE_PATH}"
          - go mod download -json
          - go build -v ./...
          - go test -v -race -cpu=1,4 ./...
          - go vet -v ./...
          - ${GOPATH}/bin/staticcheck ./...

pipelines:
  default:  # run on each push
    - step:
        image: golang:1.11
        <<: *Verify
    - step:
        image: golang:1.12
        <<: *Verify
